services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adessoworldleague-api
    ports:
      - "5000:8080"
    environment:
      - MongoSettings__ConnectionString=mongodb://mongo:27017
      - Seq__ServerUrl=http://seq:5341
    depends_on:
      mongo:
        condition: service_started
      seq:
        condition: service_started
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: adessoworldleague-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  seq:
    image: datalust/seq
    container_name: adessoworldleague-seq
    ports:
      - "5341:5341"
      - "8081:80"
    environment:
      - SEQ_FIRSTRUN_ADMINPASSWORD=Admin123!
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    restart: unless-stopped

volumes:
  mongo-data:
  seq-data:
